### ISSUE TITLE
[Custom CSS] Border around cards activated with checkbox selection

### ISSUE THREAD

**Issue by echo6ix** [stashapp/Stash-Docs#38]
**Category:**
CSS

**Script:**
```css
/* Modify card when checkbox is selected */
.grid-card.card:has(input:checked) {
   box-shadow: 0 0 0 1px var(--primary,rgba(255, 255, 255, 0.30));
}
```

**Description:**
Add a noticeable border around any cards that have been selected using the checkbox selection. Border color uses Stash's `--primary` color variable to maintain consistency with any theme that uses Stash's color variables.

**Author:**
echo6ix

**Screenshots:**
![image](https://github.com/stashapp/Stash-Docs/assets/37937507/d1c9bfe7-7d4c-48d4-b8fb-b62deb8381fc)
